!include <ntwin32.mak>



OBJS = libarchive.obj libcvrt.obj libnetserv.obj libslider.obj libverbose.obj\
      libclient.obj libdetect.obj libopaque.obj libstats.obj q330cvrt.obj\
      libcmds.obj libfilters.obj libpoc.obj libstrucs.obj q330io.obj\
      libcompress.obj liblogs.obj libsampcfg.obj libsupport.obj\
      libcont.obj libmd5.obj libsample.obj libtokens.obj\
      libctrldet.obj libmsgs.obj libseed.obj libtypes.obj\

HDRS =	libarchive.h libclient.h libcmds.h libcompress.h libcont.h libctrldet.h\
	libcvrt.h libdetect.h libfilters.h liblogs.h libmd5.h libmsgs.h\
	libnetserv.h libopaque.h libpoc.h libsampcfg.h libsampglob.h\
 	libsample.h libseed.h libslider.h libstats.h libstrucs.h libsupport.h\
	libtokens.h libtypes.h libverbose.h pascal.h platform.h q330cvrt.h\
	q330io.h q330types.h



DEFINES = -DWIN32 -DX86_WIN32 -D_CRT_SECURE_NO_DEPRECATE

all:	lib330.lib

.c.obj:
	cl /c $(DEFINES) $<

lib330.lib: $(OBJS)
	lib /OUT:lib330.lib $(OBJS)

clean:
	del *.obj
	del lib330.lib
